### ISSUE TITLE
Not an Issue, Just a question about feeding Discovery with data

### ISSUE THREAD

**Issue by Cloud9Clone** [IBM/watson-assistant-with-search-skill#11]
Hello, 

Discovery offers us a set of tools, with which we can integrate our data in the service. In this project you have used the "Upload Document" option, which indicates one document after the uploading process (Up to 50Mb file is treated as 1 document, I guess?).

But if we use the IBM Cloud Object Storage integration, the initial document size is 10Mb. So Discovery will take our whole data from COS split it in documents, each of then with maximal 10Mb?

Regards

**Comment by rhagarty** [comment]
Hello @Cloud9Clone - with the lite plan, the limits are based on number of documents. In the case of loading you own data, or like with this code pattern, loading one doc and performing SDU, you generally know if you are going to hit the limits.

With Object Storage as a data source, it all depends on the data and how discovery decides to load and separate the data out into separate docs. I would suggest trying it out to see if and when you hit your lite plan limits.

BTW, here is a good video of discovery connecting to different data sources - https://www.youtube.com/watch?v=MPCOwMgn1p4

**Comment by Cloud9Clone** [comment]
I understand. Thank you Rich. I would like to ask you something else more: 

If I have a document, which contains a JSON array of identical objects per structure, can I tell Discovery to interpret each of these as a single object, so I can perform a query on it and receive only a specific object data?
